on:
  pull_request:
    branches: [main]
    types: [opened, closed, reopened]

jobs:
  create-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Create a comment in Asana Task
    steps:
      - name: Create a comment
        uses: Asana/comment-on-task-github-action@latest
        id: createComment
        with:
          asana-secret: ${{ secrets.GITHUB_TOKEN }}
          comment-text: "{{PR_NAME}} is {{PR_STATE}}: {{PR_URL}}"
          allowed-projects: |
            1201849173362898
      - name: Get status
        run: echo "PR status is ${{ steps.createComment.outputs.status }}"
